# Generated by Django 4.0.3 on 2022-04-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0004_coaches_alter_pricelist_coach_delete_couches'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaches',
            name='photo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='number_of_training',
            field=models.IntegerField(verbose_name='Количество тренировок'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='price',
            field=models.IntegerField(verbose_name='Цена(бел/руб)'),
        ),
    ]
