# Generated by Django 4.0.3 on 2022-04-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0006_alter_coaches_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coaches',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='coach_photo'),
        ),
    ]
