# Generated by Django 4.0.3 on 2022-05-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0008_alter_coaches_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportstyle',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='style_photo'),
        ),
    ]
