# Generated by Django 4.0.3 on 2022-05-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0009_sportstyle_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Имя')),
                ('gym_information', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, default='default.jpg', upload_to='gym_photo')),
            ],
        ),
    ]
