# Generated by Django 4.0.3 on 2022-05-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0010_gym'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gym',
        ),
    ]
